project:
  type: website

website:
  title: "personal-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: courses.qmd
        text: Courses

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto



